name: Push OCI Artifacts

on:
  push:
    paths:
      - 'llm/**'
    tags:
      - 'v*'

jobs:
  push-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check for file changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            agent:
              - 'llm/agent/**'
            command:
              - 'llm/command/**'

      - uses: fluxcd/flux2/action@main

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Agent Artifact
        if: steps.filter.outputs.agent == 'true'
        run: |
          flux push artifact oci://ghcr.io/${{ github.repository }}/oc-agent:${{ github.ref_name }} --path=llm/agent --source=.

      - name: Push Command Artifact
        if: steps.filter.outputs.command == 'true'
        run: |
          flux push artifact oci://ghcr.io/${{ github.repository }}/oc-command:${{ github.ref_name }} --path=llm/command --source=.
